# referer 地址验证
my:
    config:
        refererDomain:
            - http://127.0.0.1:9091/movie-user
            - http://192.168.137.1/movie-user
            - pibigstar.com
            - mxspvip.cn
        uploadDir: ${user.dir}/../uploads
        qrcodeDir: ${user.dir}/../uploads/qrcode
        avatarDir: ${user.dir}/../uploads/avatar
        feedbackDir: ${user.dir}/../uploads/feedback
