# referer 地址验证
my:
    config:
        refererDomain:
            - http://127.0.0.1:9091/movie-user
            - http://192.168.137.1/movie-user
            - pibigstar.com
            - mxspvip.cn
